Qt: Translatification
PCSX2/pcsx2 pull request #10988
Opened 2024-03-28 16:32 UTC by kamfretoz

### Description of Changes

This PR attempts to make more untranslatable strings be translatable.

### Rationale behind Changes

Translation 100

### Suggested Testing Steps

See if the text shows up correctly, mainly the memory card section.

2024-03-28 17:16 UTC, IlDucci reviewed
I'm leaving some English grammar comments that were before the changes, just in case we can kill two birds with one stone.

2024-03-28 17:16 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +					fmt::format(TRANSLATE_FS("MemoryCard", "Could not create the memory card:\n{}"),
Should "Memory Card" be uppercased? There are more cases where it's shown as memory card, I shall not repeat those.

2024-03-28 17:16 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +													   "Memory Card will be disabed for the remainder of this session.\n"
Typo here: "disabled"

2024-03-28 17:16 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +													   "Close any other instances of PCSX2, or restart your computer\n."),
Period after line break.

2024-03-29 03:13 UTC, stenzek commented
IMO, it's not worth translating the very-infrequent errors (e.g. cannot write the superblock).
1. It'll be meaningless to the user.
2. It's going to be meaningless for support, since we don't understand those languages.

2024-03-29 09:48 UTC, kamfretoz commented
> IMO, it's not worth translating the very-infrequent errors (e.g. cannot write the superblock).

Done.

2024-04-04 09:02 UTC, IlDucci requested changes
Were all my reviews autoresolved because of some commit changes?

2024-04-04 09:02 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +					fmt::format(TRANSLATE_FS("MemoryCard", "Could not create the memory card:\n{}"),
Unresolving this question, as all issues I had were automatically resolved during commits because GitHub.

2024-04-04 09:02 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +													   "Close any other instances of PCSX2, or restart your computer\n."),
Unresolving this question, as all issues I had were automatically resolved during commits because GitHub.

2024-04-04 09:02 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +				fmt::format(TRANSLATE_FS("MemoryCard", "Failed to open memory card:\n{}"), full_path.c_str()));
"memory card" or "Memory Card" unification issue.

2024-04-04 09:02 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +						fmt::format("Failed to write memory card file:\n{}", full_path.c_str()));
"memory card" or "Memory Card" unification issue.

2024-04-04 09:02 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +						fmt::format("Failed to write memory card file:\n{}", full_path.c_str()));
"memory card" or "Memory Card" unification issue.

2024-04-04 09:04 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +													   "Close any other instances of PCSX2, or restart your computer\n."),
In this case, the final period after "computer" should be before the line break, not after.

2024-04-04 09:14 UTC, IlDucci commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +					fmt::format(TRANSLATE_FS("MemoryCard", "Could not create the memory card:\n{}"),
NOTE for myself or anyone for the future:
Sony wrote the "memory card" itself in lowercase in English and probably in Title Uppercasing for non-English languages (only confirmed for Spanish). However, the MEMORY CARD slot has the memory card part in full caps.

2024-04-04 10:01 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +					Host::ReportErrorAsync("Memory Card Read Failed", "Error reading Memory Card.");
```suggestion
					Host::ReportErrorAsync("Memory Card Read Failed", "Error reading memory card.");
```

2024-04-04 10:01 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +			Host::ReportErrorAsync("Memory Card Read Failed", "Error reading Memory Card.");
```suggestion
			Host::ReportErrorAsync("Memory Card Read Failed", "Error reading memory card.");
```

2024-04-04 10:01 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +					fname.c_str()));
```suggestion
					fname));
```

2024-04-04 10:01 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +													   "Close any other instances of PCSX2, or restart your computer\n."),
```suggestion
													   "Close any other instances of PCSX2, or restart your computer.\n"),
```
period before \n, not after

2024-04-04 10:02 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +				fmt::format("Failed to write folder Memory Card:\n{}", full_path.c_str()));
```suggestion
				fmt::format("Failed to write folder Memory Card:\n{}", full_path));
```

2024-04-04 10:02 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +			Host::ReportErrorAsync("Memory Card Creation Failed", fmt::format("Failed to write folder Memory Card superblock:\n{}", full_path.c_str()));
```suggestion
			Host::ReportErrorAsync("Memory Card Creation Failed", fmt::format("Failed to write folder memory card superblock:\n{}", full_path));
```
but it's a logging message, so doesn't really matter

2024-04-04 10:02 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +				fmt::format(TRANSLATE_FS("MemoryCard", "Failed to open memory card:\n{}"), full_path.c_str()));
```suggestion
				fmt::format(TRANSLATE_FS("MemoryCard", "Failed to open memory card:\n{}"), full_path));
```

2024-04-04 10:03 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +					Host::ReportErrorAsync(TRANSLATE_SV("MemoryCard", "Memory Card Creation Failed"),
```suggestion
					Host::ReportErrorAsync("Memory Card Creation Failed",
```
don't mix translated and non-translated messages

2024-04-04 10:05 UTC, stenzek commented on pcsx2-qt/AutoUpdaterDialog.cpp
> +		msgbox.setWindowModality(Qt::WindowModal);
I think the save state warning should probably be application modal, and block all input, increasing the chances of the user actually reading it.

(application modal should be the default)

2024-04-04 13:13 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
>  		auto fp = FileSystem::OpenManagedCFile(full_path.c_str(), "wb");
```suggestion
		Error error;
		auto fp = FileSystem::OpenManagedCFile(full_path.c_str(), "wb", &error);
```

2024-04-04 13:15 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +						fmt::format("Failed to write memory card file:\n{}", full_path.c_str()));
```suggestion
						fmt::format("Failed to write memory card file:\n{}", full_path));
```

2024-04-04 13:15 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +						fmt::format("Failed to write memory card file:\n{}", full_path.c_str()));
```suggestion
						fmt::format("Failed to write memory card file:\n{}", full_path));
```

2024-04-04 13:15 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
>  		if (!FileSystem::CreateDirectoryPath(full_path.c_str(), false))
```suggestion
    Error error;
		if (!FileSystem::CreateDirectoryPath(full_path.c_str(), false, &error))
```

2024-04-04 13:16 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +				fmt::format("Failed to write folder memory card:\n{}", full_path));
```suggestion
				fmt::format("Failed to create directory. The error was:\n{}", error.GetDescription()));
```

2024-04-04 13:17 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
>  		auto fp = FileSystem::OpenManagedCFile(Path::Combine(full_path, s_folder_mem_card_id_file).c_str(), "wb");
```suggestion
    Error error;
		auto fp = FileSystem::OpenManagedCFile(Path::Combine(full_path, s_folder_mem_card_id_file).c_str(), "wb", &error);
```

2024-04-04 13:17 UTC, stenzek commented on pcsx2/SIO/Memcard/MemoryCardFile.cpp
> +			Host::ReportErrorAsync("Memory Card Creation Failed", fmt::format("Failed to write folder memory card superblock:\n{}", full_path));
```suggestion
			Host::ReportErrorAsync("Memory Card Creation Failed", fmt::format("Failed to create superblock. The error was:\n{}", error.GetDescription()));
```

2024-04-06 12:36 UTC, merged