Qt: Simplify compat line in GameSummaryWidget
PCSX2/pcsx2 pull request #11619
Opened 2024-07-23 17:09 UTC by TheTechnician27

### Description of Changes
Get rid of extraneous icon for the compat line in GameSummaryWidget and turn the line into a read-only text field.

### Rationale behind Changes
The icon was so tiny as to be unreadable and therefore useless. The line was previously a dropdown menu that could not be changed, creating an extraneous arrow symbol on the right side of the line.

### Suggested Testing Steps
Check the game properties widget for your games.

2024-07-23 17:14 UTC, Mrlinkwii commented
can you screenshot of whats being changed :)

2024-07-23 17:20 UTC, Mrlinkwii approved these changes

2024-07-23 22:13 UTC, AmyRoxwell approved these changes
Works well on endeavourOS (Arch linux based distro)

![Screenshot_07_23_2024-26](https://github.com/user-attachments/assets/2d003da2-681b-4c23-81bc-2d0322041498)
![Screenshot_07_23_2024-25](https://github.com/user-attachments/assets/4f1a2197-e1e4-4a5a-a31b-d7c8cf76ea13)

2024-07-23 22:58 UTC, F0bes requested changes

2024-07-23 22:58 UTC, F0bes commented on pcsx2-qt/Settings/GameSummaryWidget.cpp
> +        .arg(GameList::EntryCompatibilityRatingToString(entry->compatibility_rating))
Tabs should be used for indentation instead (my diffs tabs were turned to spaces by discord :face_exhaling: )

2024-07-24 17:14 UTC, merged

2024-07-26 00:31 UTC, xujibbs commented
the change made the strings "unknown" "Playable" "Perfect" untranslatable.

2024-07-26 00:47 UTC, F0bes commented
Whoops, that's an oversight. We'll look into it.

On Thu, Jul 25, 2024, 8:31 p.m. xujibbs ***@***.***> wrote:

> the change made the strings "unknown" "Playable" "Perfect" untranslatable.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PCSX2/pcsx2/pull/11619#issuecomment-2251669127>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG7QDSCLXJBRYV5YZI32YTTZOGKGPAVCNFSM6AAAAABLK3BVO2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJRGY3DSMJSG4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>