USB: ASCII Trance Vib emulation
PCSX2/pcsx2 pull request #11616
Opened 2024-07-23 07:36 UTC by Florin9doi

### Description of Changes
ASCII Trance Vib emulation

### Rationale behind Changes

### Suggested Testing Steps
Compatibility:
| Game | Supported |
| --- | --- |
| Rez | ✅ |
| Space Channel 5 Part 2 | ✅ |
| Zettai Zetsumei Toshi | ✅ |
| Disaster Report | ❌ |
| SOS: The Final Escape | ❌ |

2024-07-23 07:48 UTC, JordanTheToaster requested changes

2024-07-23 07:48 UTC, JordanTheToaster commented on pcsx2-qt/resources/icons/black/svg/trance-vibrator-line.png
Can you make these icons SVG?

2024-07-23 07:53 UTC, JordanTheToaster commented
Also if you could write a proper PR description that would be good.

2024-07-23 09:12 UTC, Florin9doi commented on pcsx2-qt/resources/icons/black/svg/trance-vibrator-line.png
done

2024-07-27 18:25 UTC, F0bes approved these changes
LGTM. Tested Rez and it detects and uses the device. The vibration worked fine on my controller.

2024-07-27 18:25 UTC, merged