OSD: Move hardcore notification from toast to OSD
PCSX2/pcsx2 pull request #11621
Opened 2024-07-24 09:26 UTC by kamfretoz

### Description of Changes

This PR moves the Hardcore mode notification from toast to the OSD.

Before:
![Screenshot_20240724_153930](https://github.com/user-attachments/assets/58878d99-0010-4f61-b1d0-1347188937f3)

After:
![Screenshot_20240724_155918](https://github.com/user-attachments/assets/52f10897-61fc-4b17-aac2-562baac02e48)

### Rationale behind Changes

Makes it more obvious of its existence and makes it easier to read.

### Suggested Testing Steps

See if the notification shows up properly.

#### Steps to test
1. Enable Hardcore Mode
2. Run a game that has no achievements
3. Observe the notification on the top left

2024-07-24 16:24 UTC, lightningterror commented
I prefer it where it is, but that's just me.

2024-07-24 17:29 UTC, PolygonSlayer commented
Just chiming in as I was the one mentioning this in the discord.
I think if there was an option that might be good then for people who prefer the old one. For me I think anything that covers the game screen it would be nice if it was either a way to turn it off or move it. In this case you can't turn this off unless you turn RetroAchivements off entirely which is a bit annoying (at least I was unable to find an option for it).

2024-07-25 06:19 UTC, kamfretoz commented
It's more of consistencies as well, everything else already uses the top-left OSD notifications. the hardcore mode is the only one that aren't already (there are also related to connectivity to RCheevos server that still uses the toast but i choose to leave it as is because its lower-priority compared to the actual hardcore status notification).

2024-07-27 15:20 UTC, lightningterror approved these changes
Scratch what I said before, I mixed before and after comparison.

2024-07-27 15:25 UTC, F0bes commented
Just for consistency, would you be able to change the other achievement messages to use the OSD messages instead of the fullscreen UI?

"Leaderboard download failed"
"Achievements Disconnected"
etc

2024-07-27 16:30 UTC, kamfretoz commented
Done

2024-07-27 16:36 UTC, F0bes requested changes

2024-07-27 16:36 UTC, F0bes commented on pcsx2/Achievements.cpp
> +
Trailing tabs

2024-07-27 16:36 UTC, F0bes commented on pcsx2/Achievements.cpp
> +		ImGuiFullscreen::AddNotification("leaderboard_dl_fail", Host::OSD_INFO_DURATION, TRANSLATE("Achievements","Leaderboard Download Failed"), error_message, s_game_icon);
Missing a space after `"Achievements",`

2024-07-27 16:36 UTC, F0bes commented on pcsx2/Achievements.cpp
> +		ImGuiFullscreen::AddNotification("leaderboard_dl_fail", Host::OSD_INFO_DURATION, TRANSLATE("Achievements","Leaderboard Download Failed"), error_message, s_game_icon);
Missing a space after `"Achievements",`

2024-07-27 16:36 UTC, F0bes commented on pcsx2/Achievements.cpp
> +			ImGuiFullscreen::AddNotification("achievements_reconnect", Host::OSD_INFO_DURATION, TRANSLATE_STR("Achievements", "Achievements Reconnected"), TRANSLATE_STR("Achievements", "All pending unlock req
Can you split these back to two lines, it's really long

2024-07-27 16:36 UTC, F0bes commented on pcsx2/Achievements.cpp
> +			ImGuiFullscreen::AddNotification("achievements_disconnect", Host::OSD_ERROR_DURATION, TRANSLATE_STR("Achievements", "Achievements Disconnected"), TRANSLATE_STR("Achievements", "An unlock request c
Same thing, can you split these back to two lines, it's really long

2024-07-27 17:05 UTC, F0bes approved these changes
Awesome. lgtm

2024-07-27 17:05 UTC, merged