Qt/FSUI: Translation fixes
PCSX2/pcsx2 pull request #11641
Opened 2024-07-29 15:09 UTC by kamfretoz

### Description of Changes

Addresses:
- `About Window -> The "Version: " string is untranslatable`
- `Game Properties -> Details -> Type -> Type names are untranslatable.`

### Rationale behind Changes

More translation the gooder.

### Suggested Testing Steps

See if i broke anything.

2024-07-29 22:50 UTC, F0bes requested changes
Just one formatting issue.

2024-07-29 22:50 UTC, F0bes commented on pcsx2/GameList.cpp
> +	static std::array<const char*, static_cast<int>(EntryType::Count)> names = {{TRANSLATE("GameList", "PS2 Disc"), TRANSLATE("GameList","PS1 Disc"), TRANSLATE("GameList", "ELF")}};
Missing a space before "PS1 Disc"

2024-07-30 05:14 UTC, kamfretoz commented on pcsx2/GameList.cpp
> +	static std::array<const char*, static_cast<int>(EntryType::Count)> names = {{TRANSLATE("GameList", "PS2 Disc"), TRANSLATE("GameList","PS1 Disc"), TRANSLATE("GameList", "ELF")}};
Done

2024-07-31 16:42 UTC, F0bes approved these changes
lgtm

2024-07-31 16:42 UTC, merged