OSD: Add GPU Info
PCSX2/pcsx2 pull request #11808
Opened 2024-09-13 07:51 UTC by kamfretoz

### Description of Changes

This PR adds the currently used GPU string name to the OSD as part of the HW Info settings.

![RetroBar_80qbJ2tbcN](https://github.com/user-attachments/assets/6a0cff6b-afa2-4cfe-abad-9f3a75484d74)

### Rationale behind Changes

### Suggested Testing Steps

2024-09-13 11:13 UTC, JordanTheToaster approved these changes

2024-09-14 18:52 UTC, F0bes requested changes
Worked fine on Windows with d3d11,d3D12,OpenGL, and Vulkan.
Just fix the tab and it LGTM.

2024-09-14 18:52 UTC, F0bes commented on pcsx2/ImGui/ImGuiOverlays.cpp
> +		}
Tab after the curly bracket.

2024-09-15 09:45 UTC, kamfretoz commented on pcsx2/ImGui/ImGuiOverlays.cpp
> +		}
Done.

2024-09-15 12:23 UTC, F0bes approved these changes

2024-09-15 12:24 UTC, merged