HostFS: Retain File Handles in Save States
PCSX2/pcsx2 pull request #11875
Opened 2024-10-05 18:34 UTC by pips3

### Description of Changes

[SAVEVERSION+]
Save host file handle and position information in save states, and reopen handles at the correct position when states are loaded.

Note: This is my first contribution, and I am still learning PCSX2's codebase, as well as best C++ practices. Criticism is appreciated!

### Rationale behind Changes

Currently, if a homebrew/game uses Host Filesystem to stream files, using save states can cause issues. For example if the streamed file is audio, it can cause audio to be desynced, stop entirely or even play the incorrect song. This is caused by open file handles no longer existing or the file offset pointer being different when loading a savestate.
### Suggested Testing Steps

@penguino118 has graciously created a homebrew elf that demonstrates this issue. The program streams audio from `GTA.wav`and `HMU.wav`. (Assets are copyright free/public domain)
[hostfs_handle_test.zip](https://github.com/user-attachments/files/17266999/hostfs_handle_test.zip)

Expected behaviour on master:

1. Boot `tutorial_06.elf`. Press X to begin.
2. Save a state while a song is playing.
3. Wait a few seconds for the song to progress, then load the state you just made.
4. The song will continue playing from the point it was at before the state was loaded. (Bad)
5. Press X to Switch song. Load the state again. The song you switched to continue to play instead of the one the state was saved on. (Bad!)
6. Reset the elf, do NOT press X to begin. Load the state. The song will endlessly stutter. (Bad!!)

Expected behaviour on this branch:

1. Open `tutorial_06.elf`. Press X to begin.
2. Save a state while a song is playing.
3. Wait a few seconds for the song to progress, then load the state you just made.
4. The song will play from the point it was at when the state was made. (Good)
5. Press X to Switch song. Load the state again. It will play the song that the state was saved on. (Good)
6. Reset the elf, do NOT press X to begin. Load the state. The song will play. (Good)

2024-10-05 20:04 UTC, F0bes requested changes
Thanks, this is a great addition. I just noticed a couple issues and warnings :)

2024-10-05 20:04 UTC, F0bes commented on pcsx2/IopBios.cpp
> +			R3000A::HostFile::open(&file, handle.full_path, handle.flags, handle.mode);
Can you check the return of this open call or check if `file` is `nullptr`? It's probably best to remove the handle if this is the case. 
You can run into issues if you load a state after renaming / removing a file that was previously saved.

Also I'd add a warning in the console with the file path via `Console.Warning(...)` so people know why their state isn't working as intended.

2024-10-05 23:23 UTC, pips3 commented on pcsx2/IopBios.cpp
> +			long pos;
Ooo that's not good, thanks. I'll have to remember to test on linux as well in the future :P

2024-10-06 13:29 UTC, F0bes commented on pcsx2/IopBios.cpp
> +			u32 fd = R3000A::handles[i].fd_index;
can be const, otherwise looks good to me.

2024-10-06 14:32 UTC, kamfretoz approved these changes
LGTM, tested on both Master and PR.

2024-10-06 14:40 UTC, JordanTheToaster approved these changes

2024-10-07 13:56 UTC, merged