iR5900: Remove mid block jumping
PCSX2/pcsx2 pull request #12056
Opened 2024-12-03 10:20 UTC by JordanTheToaster

### Description of Changes
Removes JIT mid block jumping.

### Rationale behind Changes
Vroom.

### Suggested Testing Steps
Test any games you'd like and see if it breaks anything.

2024-12-03 12:20 UTC, kamfretoz approved these changes

2025-01-12 12:06 UTC, Mrlinkwii commented
A small performance increase across the board

2025-01-12 15:19 UTC, kamfretoz approved these changes
Some benchmarks

![CapFrameX_EekgyHTYcN](https://github.com/user-attachments/assets/2be45688-6775-447b-ab5c-3614e4fb7f88)

![CapFrameX_Vtp9KqMnwT](https://github.com/user-attachments/assets/0c116408-3738-483a-8d16-d765345dfd97)

![CapFrameX_fDJaJduY9F](https://github.com/user-attachments/assets/7799879a-591a-48c2-b983-e4c3ebe07f2b)

2025-01-12 22:28 UTC, F0bes requested changes

2025-01-12 22:28 UTC, F0bes commented on pcsx2/x86/ix86-32/iR5900.cpp
> +	//WARNING_LOG("Compiling block {:08X} => {:08X}", startpc, s_nEndBlock);
Remove this comment please.

2025-01-12 22:40 UTC, F0bes approved these changes

2025-01-12 22:40 UTC, merged