Debugger: Add Reset button
PCSX2/pcsx2 pull request #12082
Opened 2024-12-13 02:35 UTC by allkern

### Description of Changes
Add a handy 'Reset' button next to the 'Run' button.

### Rationale behind Changes
As an emulator developer, resetting while working with the debugger is a pretty common occurrence. Having to reach out to the main window, then clicking on System -> Reset is somewhat cumbersome.

### Suggested Testing Steps
Open debugger, click on the 'Reset' button, voila!

2024-12-13 11:50 UTC, kamfretoz approved these changes

2024-12-13 20:54 UTC, TheTechnician27 requested changes
PR works as intended, and the code to my untrained eye looks good. However (and I think fobes might agree with me here), I think that it works too well as intended. The button, directly adjacent to the pause button, resets the game immediately on one click. This is, in my opinion, an accident waiting to happen, especially because people using the debugger are the type spend a lot of time trying to meticulously set something up in-game. I think there at least needs to be a prompt confirming to the end user that they want to reset the game. I know this defeats some of the convenience if you're repeatedly reseting the game for some reason, but this is a trade-off for what I imagine is a very small portion of users compared to the much higher likelihood that a user generally doesn't want to reset the game from within the debugger.

2024-12-13 23:31 UTC, chaoticgd commented
Just as a heads up, I'm currently working on an overhaul of the debugger's UI. If I end up finishing it I'll probably do another pass on how the toolbars work anyway e.g. I could add options to show/hide them and move them around anywhere. I think that would solve the problem nicely, so for now maybe just put the Reset button further away from the Pause button.

2024-12-13 23:40 UTC, F0bes commented
![image](https://github.com/user-attachments/assets/0c0630f5-2b61-4609-aadd-0f1b9924ca93)
What if something like this is done (But fix the parent QAction and remove the top level reset action)

2024-12-15 14:32 UTC, allkern commented
> PR works as intended, and the code to my untrained eye looks good. However (and I think fobes might agree with me here), I think that it works too well as intended. The button, directly adjacent to the pause button, resets the game immediately on one click. This is, in my opinion, an accident waiting to happen, especially because people using the debugger are the type spend a lot of time trying to meticulously set something up in-game. I think there at least needs to be a prompt confirming to the end user that they want to reset the game. I know this defeats some of the convenience if you're repeatedly reseting the game for some reason, but this is a trade-off for what I imagine is a very small portion of users compared to the much higher likelihood that a user generally doesn't want to reset the game from within the debugger.

I agree, I definitely wouldn't mind moving the reset button elsewhere as long as it's there, maybe to the right of 'Step Out'? F0bes suggestion also looks nice. I don't really know Qt that much so I wouldn't know how to pull it off, but you're welcome to change the code however you like

2025-04-26 08:00 UTC, closed without merging

2025-04-26 08:00 UTC, lightningterror commented
Reset button was added in https://github.com/PCSX2/pcsx2/pull/12241