Rename input profile
PCSX2/pcsx2 pull request #12111
Opened 2024-12-23 01:43 UTC by rtavarez98

### Description of Changes
Adds feature to change a controller input profile and automatically updates the name in all games using the profile.

### Rationale behind Changes
Resolves #6507

### Suggested Testing Steps
Rename an existing input profile that's assigned to at least one game and check if it's been updated in a game's settings.

2024-12-23 01:52 UTC, Mrlinkwii commented
A very small thing , can the commit have the prefix of UI:

2024-12-23 11:10 UTC, Mrlinkwii commented
seems to working good here on linux , its seems the Mac ci has failed

2024-12-23 12:46 UTC, TheLastRar commented
Mac CI fails with;
```
../../pcsx2-qt/Settings/ControllerSettingsWindow.cpp:204:52: error: no member named 'recursive_directory_iterator' in namespace 'std::filesystem'
        for (const auto& game_settings : std::filesystem::recursive_directory_iterator(game_settings_dir))
```
So you are missing the `<filesystem>`
Not that we don't use std:;filesystem anywhere else, and I would like additional testing on windows with unicode paths.


To better match existing PCSX2 code, I would suggest you instead opt for using our own FileSystem functions (in `common/FileSystem.h`). We have the following function which I think will suit your needs;
`FindFiles(const char* path, const char* pattern, u32 flags, FindResultsArray* results)`

2024-12-24 17:37 UTC, Mrlinkwii approved these changes

2024-12-27 11:48 UTC, JordanTheToaster approved these changes

2024-12-27 19:31 UTC, F0bes requested changes

2024-12-27 19:31 UTC, F0bes commented on pcsx2-qt/Settings/ControllerSettingsWindow.ui
> +	   <item>
Indenting with tabs instead of spaces.

2024-12-28 16:22 UTC, F0bes approved these changes
Code LGTM

2024-12-28 16:22 UTC, merged