Settings/Log: Print advanced settings warning on the log
PCSX2/pcsx2 pull request #12124
Opened 2024-12-27 12:16 UTC by kamfretoz

### Description of Changes

This PR adds a log entry that warns the user through the log if they have advanced options enabled.
Preview:
![image](https://github.com/user-attachments/assets/b230d211-5192-4fac-8c4f-4fee8bfeb01c)

### Rationale behind Changes

Helps with user support in the event a user has messed around with the advanced settings.

### Suggested Testing Steps

See if the warning shows up correctly if the advanced settings are enabled. Also checks when its off too, or when the value is absent from the ini file.

2024-12-27 12:32 UTC, JordanTheToaster approved these changes

2024-12-27 19:00 UTC, Mrlinkwii approved these changes
![image](https://github.com/user-attachments/assets/d1ec86fd-fb27-412f-b2dd-6a3e451232a4)
looks good to me

2024-12-27 19:30 UTC, F0bes requested changes

2024-12-27 19:30 UTC, F0bes commented on pcsx2/VMManager.cpp
> +	if (advanced_settings)
```suggestion
	if (Host::GetBaseBoolSettingValue("UI", "ShowAdvancedSettings", false))
```
Or make it const.

2024-12-27 22:04 UTC, kamfretoz commented on pcsx2/VMManager.cpp
> +	if (advanced_settings)
Done.

2024-12-27 22:19 UTC, kamfretoz commented
Also adjusted the log formatting a bit to be more consistent.

Before:
![image](https://github.com/user-attachments/assets/cf0049ed-1fed-4d00-8a0a-d0b112144785)

After:
![image](https://github.com/user-attachments/assets/887501f5-3af0-486f-bd86-7f7691b7c00c)

2024-12-28 11:40 UTC, Mrlinkwii approved these changes

2024-12-28 16:16 UTC, F0bes requested changes

2024-12-28 16:16 UTC, F0bes commented on pcsx2/R3000AInterpreter.cpp
> +		DevCon.WriteLn(Color_Gray, ":R3000 Debugger: Branch to 0x890 (SYSMEM). Clearing modules.");
You've added a colon to the start of this string

2024-12-28 16:25 UTC, F0bes approved these changes
LGTM

2024-12-28 16:25 UTC, merged