Add support for OpenPS2Loader VirtualMemoryCards
PCSX2/pcsx2 pull request #2995
Opened 2019-06-18 02:50 UTC by KrossX

As requested on Issue #2959, this adds some basic support to OPL VMC files (.bin) that use 512 bytes pages. Normal pages are 528 bytes long, those extra 16 bytes contain 12 bytes of ECC data.

[PS2 Memory Card File System](https://www.psdevwiki.com/ps3/PS2_Savedata#Memory_card_PS2_.28original.29)

On load, the OPL card is converted to a new temporal file in PCSX2's RAW format and ECC is calculated per page. On close, the reverse is done overwriting the original file and deleting the temporal one.

2019-06-18 17:14 UTC, ssakash commented on pcsx2/gui/MemoryCardFile.cpp
> +	static u8 column_parity_mask[256];
I know these are default zero initialized, but coverity is picky about it.

2019-06-30 14:37 UTC, lightningterror commented
Is this ready? Was it tested if it works properly?

2019-06-30 22:52 UTC, KrossX commented
It is not ready, and I would've liked some tests but testers will take their time. Check back in a few months or so.

2019-08-15 19:50 UTC, jLynx commented
Are you still having checksum issues with the .bin files?

2019-08-15 20:03 UTC, KrossX commented
Checksum issues? OPL VMCs can already be used on this branch. It just needs testing.

2019-08-15 20:13 UTC, jLynx commented
Oh sorry, my mistake. I though you said in another post you were having checksum issues with it. but looking back I cant find it so I must have imagined it haha

2019-08-15 20:22 UTC, KrossX commented
There are checksum issues with the format but as the PR description says, the extra bytes are generated on load and removed on save. OPL VMUs already work on my tests, but I need tests from users of such setups.

2019-08-16 04:42 UTC, jLynx commented
I just tested with a few savegames and it seems to run the .bin files perfectly!

2020-05-21 21:10 UTC, KrossX commented on pcsx2/gui/MemoryCardFile.cpp
> +			if (buffer) {
How about now? No need to worry about fancy `new`.

2020-05-21 21:12 UTC, KrossX commented on pcsx2/gui/MemoryCardFile.cpp
> +						fout.Write(cb, 1);
First suggestion worked.

2020-11-19 22:40 UTC, refractionpcsx2 requested changes

2020-11-19 22:40 UTC, refractionpcsx2 commented on pcsx2/gui/Panels/MemoryCardListPanel.cpp
> +		wxDir::GetAllFiles( filename, &memcardList, L"*.bin", wxDIR_FILES);
can you put a space after wx_DIR_FILES?

2020-11-19 22:40 UTC, refractionpcsx2 commented on pcsx2/gui/MemoryCardFile.cpp
> +			{
put the bracket on the same line as the if to match the rest of the file, also space between if and (

2020-11-19 22:41 UTC, lightningterror commented
Or just run clang on the entire file, note you can set clang to ignore the arrays.

2020-11-19 22:42 UTC, refractionpcsx2 commented
Or clang them.

2020-11-24 12:53 UTC, KrossX commented
Clang-format seems to have made, quite a lot of changes.

2020-11-24 13:50 UTC, refractionpcsx2 commented
It looks great, except the massacre it did to the parity tables xD

2020-11-24 14:10 UTC, KrossX commented
How about now?

2020-11-24 14:27 UTC, refractionpcsx2 commented
That's better on the eye yea :)

2021-01-08 23:47 UTC, merged