Lilypad: Remove psx/ps1 emulator compatibility
PCSX2/pcsx2 pull request #3323
Opened 2020-04-24 15:23 UTC by lightningterror

Same as https://github.com/PCSX2/pcsx2/pull/3274

2020-05-25 16:09 UTC, orbea commented
I'm just curious, can you elaborate on what exactly is being removed in this PR?

2020-05-25 16:19 UTC, KrossX commented
Compatibility with the plugin specs for PS1 emulators, and all the workarounds for PS1 emulators as well.

2020-09-19 18:49 UTC, GovanifY requested changes
There is some mentions of PS1 mouse that aren't removed in Lilypad.cpp, Tooltips.cpp, Config.cpp and resource.h

2020-09-19 18:50 UTC, GovanifY commented on plugins/LilyPad/Config.cpp
>      L"PS1 Mouse",
Eg a reference there

2020-09-19 18:59 UTC, RedDevilus commented
Summarised:
Config.cpp

L2133-2134
```
else if (config.padConfigs[port][slot].type == MousePad)
                psp.pszTemplate = MAKEINTRESOURCE(IDD_CONFIG_PS1_MOUSE);
```
Lilypad.rc

L325
```
IDD_CONFIG_PS1_MOUSE DIALOGEX 0, 0, 424, 283
```
L531
```
IDD_CONFIG_PS1_MOUSE, DIALOG
```
Lilypad.cpp
Mentions of MODE_PS1_MOUSE
L89
`#define MODE_PS1_MOUSE 0x12`
L798
 `pads[port][slot].mode = MODE_PS1_MOUSE;`
L1207-1208
```
 DEBUG_OUT(MODE_PS1_MOUSE);
                        return MODE_PS1_MOUSE;
```
Resource.h
L15
`#define IDD_CONFIG_PS1_MOUSE            0x70`

Tooltips.cpp
L54-55
```
  L"\"PS1 Mouse\" emulates the Playstation Mouse. This controller can only be used in a number of PS1 games like \"Command & Conquer: Red Alert\" and \"Myst\".\n\n"
                   L"\"neGcon\" emulates a controller that can be used in a number of PS1 games and PS2 games like the \"Ridge Racer\" and \"Ace Combat\" series.";
```

2020-09-20 17:19 UTC, merged