Got ps1 mode init function to exist in correct location. Added stubbed reset for spu that currently breaks sound if used
PCSX2/pcsx2 pull request #3532
Opened 2020-07-09 19:55 UTC by kenshen112

This is a simple fix that moves ps1 mode initalizer to hwWrite.cpp and disables the incorrect CDVD one

2020-07-10 15:30 UTC, turtleli commented on plugins/spu2-x/src/SndOut.h
> +static int SampleRate = 48000;
This change means that every translation unit that includes this header will have a separate copy of the variable. Any modification to this variable will only be local to that translation unit and not global.

2020-09-19 21:33 UTC, refractionpcsx2 requested changes

2020-09-19 21:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/SndOut.cpp
> +    printf("A Reset \n");
Can you remove this, not needed beyond your own debugging.

2020-09-19 21:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/PS2E-spu2.cpp
> +#elif defined(PCSX2_DEVBUILD)int SampleRate = 48000;
What's going on here?

2020-09-19 21:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/PS2E-spu2.cpp
> +
Remove the extra line

2020-09-19 21:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/PS2E-spu2.cpp
> +
Remove the extra line

2020-09-19 21:33 UTC, refractionpcsx2 commented on pcsx2/ps2/pgif.cpp
> +        	Console.WriteLn( "\n\r PGIF REVERSE !!! DATA write 0x%08X = 0x%08X  IF_CTRL= %08X   PGPU_STAT= %08X  CmdCnt 0x%X \n\r",  addr, data,  getUpdPgifCtrlReg(),  getUpdPgpuStatReg(), pgifCmdRbC.co
Would you like to comment this out again

2020-09-19 21:33 UTC, refractionpcsx2 commented on pcsx2/Hw.cpp
> +
remove extra line here

2020-09-19 21:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/SndOut.h
> +
Remove extra line

2020-09-19 21:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/Windows/Spu2-X.def
> +	SPU2ps1reset        @32
Tabs Vs Spaces

2020-09-20 17:04 UTC, GovanifY commented
I took the liberty of fixing this PR according to your review instead of @kenshen112 I'm going to rebase it now.

2020-09-20 23:33 UTC, refractionpcsx2 requested changes

2020-09-20 23:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/PS2E-spu2.cpp
> +	SampleRate = 48000;
Fix spacing

2020-09-20 23:33 UTC, refractionpcsx2 commented on plugins/spu2-x/src/PS2E-spu2.cpp
> +	SampleRate = 44100;
Fix spacing

2020-09-21 00:03 UTC, refractionpcsx2 approved these changes

2020-09-21 00:04 UTC, merged

2020-09-21 04:11 UTC, lightningterror commented on pcsx2/ps2/pgif.cpp
> +		// 	Console.WriteLn( "\n\r PGIF REVERSE !!! DATA write 0x%08X = 0x%08X  IF_CTRL= %08X   PGPU_STAT= %08X  CmdCnt 0x%X \n\r",  addr, data,  getUpdPgifCtrlReg(),  getUpdPgpuStatReg(), pgifCmdRbC.count
Spacing.