Add GHC Filesystem
PCSX2/pcsx2 pull request #3999
Opened 2020-12-12 19:49 UTC by kenshen112

This is a PR to add GHC filesystem to pcsx2 common utilittes

2020-12-12 20:16 UTC, xTVaser commented
Thoughts on putting this into `3rdparty` instead as it is a 3rdparty dependency?

2020-12-12 20:29 UTC, arcum42 commented
Yeah, given we didn't write it, 3rdparty would be a better location. While it is just one file, it's a third party file, and Utilities is mostly things we wrote. I can think of an exception or two, but then, maybe any exceptions should be moved, too...

2020-12-12 22:07 UTC, kenshen112 commented
Roger

2020-12-13 02:56 UTC, tellowkrinkle commented
Thoughts on using a directory structure more like
```
3rdparty
└── filesystem
    ├── CMakeLists.txt
    ├── filesystem.vcxproj
    ├── filesystem.vcxproj.filters
    └── include
        └── ghc
            ├── filesystem.hpp
            └── fs_std.hpp
```

2020-12-13 17:06 UTC, tadanokojin commented on common/include/Utilities/filesystem.h
> +//---------------------------------------------------------------------------------------
duplicate file

2020-12-13 17:06 UTC, tadanokojin commented on pcsx2/CMakeLists.txt
> +	fmt::fmt
Unnecessary formatting change

2020-12-13 17:06 UTC, tadanokojin commented on pcsx2/CMakeLists.txt
> +	../3rdparty/include
Unnecessary formatting change

2020-12-23 18:59 UTC, TheLastRar commented
What is the status of this pr?

2020-12-28 19:39 UTC, xTVaser requested changes
Can we get these commits squashed perhaps as follows:
- deps: Add ghc::filesystem header
- vs: Add new 3rdparty include folder to project properties
- cmake: Configure new 3rdparty include folder

Other than cleaning up the commits I don't see a reason for this to be held up.  
- It's just adding a new library that is unused (yet)
- CI is building successfully so project config changes were successful.
- And it's already being used successfully here https://github.com/PCSX2/pcsx2/pull/4005 so the new library should be usable by whoever needs it once merged.

2021-01-02 18:47 UTC, merged