Restore Decode_XA.h
PCSX2/pcsx2 pull request #4976
Opened 2021-11-04 03:20 UTC by kenshen112

### Description of Changes

Restores a file from pcsx. The structures were still in our code but had been strangely moved to cdrom.h where they don't belong
### Rationale behind Changes

Better code placement.
### Suggested Testing Steps

N/A

2021-11-04 05:01 UTC, arcum42 commented
If those structures aren't used at all, wouldn't deleting them be the better code placement?

Also, am I missing something, or is the xa_decode_sector function in that header not actually defined anywhere in Pcsx2?

2021-11-04 05:10 UTC, kenshen112 commented
No the function isn't defined. This would be the eventual lead into restoring CdXa support since we have ps1 mode. Assuming I can ever figure it out... Or someone else comes by

2021-11-04 06:02 UTC, arcum42 commented
That makes a little more sense, though I'd probably comment out the function in the header until it actually has a matching function, presumably some variation of the code in here:
https://github.com/grumpycoders/pcsx-redux/blob/main/src/core/decode_xa.cc

My other concern, really, would be that this removes Xa from cdrStruct, and cdr, which is a cdrStruct, is frozen, so I could potentially see this being a savestate version bump...

2021-11-04 08:09 UTC, refractionpcsx2 commented
Wouldn't it be better to restore this in a pr which restored xa functionality? Seems strange having a pr to restore a file to do absolutely nothing and it's not ideal for code cleanliness to have redundant stuff laying around. What if you never get around to restoring the xa functionality?

Anyway, that's my 2c

2021-11-04 08:36 UTC, lightningterror commented on pcsx2/CDVD/Decode_XA.h
> +//============================================
Missing copyright header.

2021-11-05 05:41 UTC, F0bes commented on pcsx2/CDVD/Decode_XA.h
> +#endif
Missing the newline at the end of file.

2021-11-05 05:41 UTC, F0bes commented on pcsx2/pcsx2.vcxproj
> +</Project>
Missing the newline at the end of file.

2021-11-05 05:41 UTC, F0bes commented on pcsx2/pcsx2.vcxproj.filters
> +</Project>
Missing the newline at the end of file.

2021-11-12 01:59 UTC, lightningterror requested changes
No need to have it included now if it does nothing, better comment it out in the file it currently is.

2021-11-29 01:41 UTC, refractionpcsx2 commented
Remove the new file please.

2021-11-29 01:42 UTC, kenshen112 commented
I'll make a seperate PR for that. This was to restore the header file. Which obviously wasn't accepted

2021-11-29 01:42 UTC, closed without merging