Gamedb : add various fixes for various games
PCSX2/pcsx2 pull request #5023
Opened 2021-11-16 16:20 UTC by Mrlinkwii

### Description of Changes

Adds various patches which fixes games 
### Rationale behind Changes

fixes said games 
### Suggested Testing Steps

look at the  CI and test said games

2021-11-16 21:15 UTC, RedDevilus requested changes
Some minor stuff you could adjust.

2021-11-16 21:15 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    vuClampMode: 2 #Fixes currupt textures.
```suggestion
    vuClampMode: 2 # Fixes currupt textures. 
```

2021-11-16 21:15 UTC, RedDevilus commented on bin/GameIndex.yaml
> +        author=prafull
```suggestion
        author=Prafull
```

2021-11-16 21:15 UTC, RedDevilus commented on bin/GameIndex.yaml
> +        author=prafull
```suggestion
        author=Prafull
```

2021-11-16 21:15 UTC, RedDevilus commented on bin/GameIndex.yaml
> +        //Skip sceipusync
// with spaces everywhere too

2021-11-16 21:15 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    vuClampMode: 2 #Fixes currupt textures.
```suggestion
    vuClampMode: 2 # Fixes currupt textures.
```

2021-11-16 21:15 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    vuClampMode: 2 #Fixes currupt textures.
```suggestion
    vuClampMode: 2 # Fixes currupt textures. 
```

2021-11-16 22:22 UTC, Rumi-Larry commented on bin/GameIndex.yaml
> +    vuClampMode: 2 # Fixes currupt textures.
typo: "corrupt"

2021-11-16 22:24 UTC, Rumi-Larry commented on bin/GameIndex.yaml
> +    vuClampMode: 2 # Fixes currupt textures.
ditto

2021-11-16 22:24 UTC, Rumi-Larry commented on bin/GameIndex.yaml
> +    vuClampMode: 2 # Fixes currupt textures.
ditto

2021-11-17 16:31 UTC, RedDevilus commented
One last improvement is to change
Disc1 and Disc2 entries in the serial name to

[Disc1of2]

[Disc2of2]

It's consistent with the other entries in the GameDB

2021-11-17 16:36 UTC, RedDevilus commented
At least Onimusha will look less like the deep-fried meme in the menus.

2021-11-17 17:38 UTC, RedDevilus commented on bin/GameIndex.yaml
> +  name: "Onimusha - Dawn of Dreams [Disc1 of 2]"
```suggestion
  name: "Onimusha - Dawn of Dreams [Disc1of2]"
```

2021-11-17 17:38 UTC, RedDevilus commented on bin/GameIndex.yaml
> +  name: "Onimusha - Dawn of Dreams [Disc2 of 2]"
```suggestion
  name: "Onimusha - Dawn of Dreams [Disc2of2]"
```

2021-11-17 17:39 UTC, RedDevilus requested changes
Either we do spaces everywhere or remove spaces for saying which disc it is.

2021-11-17 18:00 UTC, RedDevilus approved these changes

2021-11-20 10:42 UTC, JordanTheToaster approved these changes

2021-11-21 03:03 UTC, merged