Gamedb :add 'GIFFIFOHack' to 'FIFA 2005'
PCSX2/pcsx2 pull request #5049
Opened 2021-11-21 18:22 UTC by Mrlinkwii

### Description of Changes

add 'GIFFIFOHack' to 'FIFA 2005
### Rationale behind Changes

The hack helps the game 
### Suggested Testing Steps

look at CI

2021-11-21 23:22 UTC, JordanTheToaster approved these changes

2021-11-22 10:43 UTC, RedDevilus commented on bin/GameIndex.yaml
> +  region: "PAL"
```suggestion
  region: "PAL-M7"
```

2021-11-22 10:44 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    - GIFFIFOHack # Partily fixed grpahical issues also needs EE cycle rate + 3.
```suggestion
    - GIFFIFOHack # Partially fixes graphical issues also needs EE cycle rate + 3.
```

2021-11-22 10:44 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    - GIFFIFOHack # Partily fixed grpahical issues also needs EE cycle rate + 3.
Copy to the rest of the comments

2021-11-22 13:54 UTC, RedDevilus requested changes

2021-11-22 13:54 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    eeClampMode: 3 # Fixes black screen
```suggestion
    eeClampMode: 3 # Fixes black screen.
```

2021-11-22 13:54 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    eeClampMode: 3 # Fixes black screen
```suggestion
    eeClampMode: 3 # Fixes black screen.
```

2021-11-22 13:54 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    eeClampMode: 3 # Fixes black screen
```suggestion
    eeClampMode: 3 # Fixes black screen.
```

2021-11-22 13:54 UTC, RedDevilus commented on bin/GameIndex.yaml
> +    - GIFFIFOHack # Partially fixes graphical issues also needs EE cycle rate +
```suggestion
    - GIFFIFOHack # Partially fixes graphical issues also needs EE cycle rate + 3.
```

2021-11-22 15:32 UTC, refractionpcsx2 commented on bin/GameIndex.yaml
> +    - EETimingHack
missing comment

2021-11-22 15:36 UTC, Mrlinkwii commented on bin/GameIndex.yaml
> +    - EETimingHack
Done :+1:

2021-11-22 15:39 UTC, refractionpcsx2 commented on bin/GameIndex.yaml
> +    - GIFFIFOHack # Partially fixes graphicalissues also needs EE cycle rate + 3.
graphicalissues

2021-11-22 15:41 UTC, merged