GS/Vulkan: Use VK_EXT_unrestricted_depth_range where available
PCSX2/pcsx2 pull request #5518
Opened 2022-02-12 05:57 UTC by stenzek

### Description of Changes

This improves depth precision, especially when conversion is required,as we don't need to normalize it to the 0..1 range.

Sadly, it doesn't improve precision in rendering alone (e.g. Quake 3), since the clip-space Z still needs to be normalized (the extension effectively multiplies it in the viewport transform).

Fixes z-fighting in reflections in DBZ BT3, maybe others?

### Rationale behind Changes

Fixing bugs.

### Suggested Testing Steps

Test games with z-fighting, make sure there's no regressions in others which use format conversions.

2022-02-12 07:49 UTC, refractionpcsx2 commented
DBZ BT3 fixed as noted

Master:

![image](https://user-images.githubusercontent.com/6278726/153702338-9edce45f-24ae-47c5-aee0-f5d2d69d6360.png)

PR:

![image](https://user-images.githubusercontent.com/6278726/153702349-c6dfe31d-9478-434b-9250-ae3f93165217.png)


Toro to Kyuujitsu as noted in #4674 fixed in Vulkan.

Master:

![image](https://user-images.githubusercontent.com/6278726/153702423-cbaec443-d20b-46f2-8ce1-1978ecc57842.png)

PR:

![image](https://user-images.githubusercontent.com/6278726/153702432-4031c8a7-625e-4f61-8200-f9dc9d1346bb.png)

2022-02-12 09:32 UTC, gilderoylockhart01 commented
Wow, you fixed a bug in the aura homebrew that existed since PCSX2 was created ^^:

![image](https://user-images.githubusercontent.com/90222976/153705814-6233227a-73fe-4b0c-98e7-45f6def57ee1.png)

2022-02-12 09:35 UTC, gilderoylockhart01 commented
Congratulation, you fixed a bug that existed since PCSX2 existed ^^:

![image](https://user-images.githubusercontent.com/90222976/153705930-e2da0d13-2d03-4bff-b511-ab53580a1982.png)

2022-02-12 14:09 UTC, DonelBueno commented
> Congratulation, you fixed a bug that existed since PCSX2 was create ^^:
> 
> ![image](https://user-images.githubusercontent.com/90222976/153705930-e2da0d13-2d03-4bff-b511-ab53580a1982.png)

What game is it?

2022-02-12 14:10 UTC, refractionpcsx2 commented
> What game is it?

It's a homebrew called Aura for Laura

2022-02-12 22:02 UTC, tellowkrinkle commented
I don't see how precision should be changed at all by multiplying by a power of 2 (like `exp(-32)`), that should only affect the exponent and not touch the mantissa at all.

Are you sure the accuracy improvement here isn't actually due to the changes to the depth ↔︎ color conversion functions?
(If so, we can get that accuracy without dealing with multiple depth representations across different APIs)

2022-02-12 22:54 UTC, tellowkrinkle commented
Okay I tested our current algorithm, and while I expected it to break on weird edge cases, I didn't expect it to break on *literally every nonzero integer*

[Test and results here](https://gist.github.com/tellowkrinkle/47f9302a2e869a9d965b8ab5a9d47306) (Yes, it's in Metal.  Sorry.  Results are included so you don't need to run it.)

Looking back on it, the issue mainly stems from us treating values of `1/255` and `1/256` the same.  The depth → rgba conversion grabs each 0-255 chunk divided by *256* and returns them.  This works fine for values from 0 to 0x80, but for 0x81 to 0xff, the value is rounded down when being converted to unorm.
In the rgba → depth conversion, we multiply by 0xff and convert to integer.  But the unorm → float algorithm doesn't give exact results, and it appears to (on my AMD GPU) give the float 0x3f008080 for 0x80, while the proper float for 128/255 is 0x3f008081.  Because of this, multiplying by 0xff and converting to integer rounds *down* to 0x7f.

So we should definitely test fixing the conversion functions before we attempt unrestricted depth, as I don't think that's the issue

2022-02-13 02:49 UTC, stenzek commented
Refraction and I actually tested using integers for converting the incoming colour values and found that it wasn't sufficient for DTZ BT3 (at least with the conversions it uses; rgba8->float24). So while it does sound like there's an issue with the float-based conversion, I was trying to leave that path unchanged in this PR.

2022-02-13 13:14 UTC, lightningterror commented on bin/resources/shaders/opengl/tfx_fs.glsl
> +		uint d = uint(fetch_c(uv).r * exp2(32.0f));
Spaces instead of tabs.

2022-02-13 13:29 UTC, lightningterror requested changes
Forgot to change the dx11 equivalent shaders in tfx.fx.

2022-02-13 15:17 UTC, lightningterror approved these changes

2022-02-13 16:04 UTC, lightningterror requested changes
Depth seems broken on dx11 on dbz bt3.

2022-02-14 14:50 UTC, refractionpcsx2 commented
@gilderoylockhart01 yes this PR doesn't aim to fix *MOST* z-fighting problems, it's very specific ones, usually localised (so they appear as thin lines rather than missing polys).

2022-02-14 16:52 UTC, stenzek commented
I made a note of that in the OP. This only affects depth buffer round trips.

2022-02-14 19:05 UTC, refractionpcsx2 commented
@gilderoylockhart01 what bug in The Sims 2? Have you got comparison shots?

2022-02-15 09:40 UTC, lightningterror approved these changes

2022-02-15 09:41 UTC, merged