Cue file support
PCSX2/pcsx2 pull request #5772
Opened 2022-03-28 01:55 UTC by kenshen112

### Description of Changes

Adds support for cue files from DuckStation parser refactored into CDVDAccess

### Rationale behind Changes

To add support for PlayStation 1 cue files. And for PlayStation 2 games that are multitrack

### Suggested Testing Steps

Run bin or cue file. See if game goes brr

ToDo:
Need to handle audio tracks for CD-DA and any ps2 games that need it. Figuring out the ps2 logic to this will be one hell of a challenge.

Need to add support for chd cue logic.

2022-03-28 02:27 UTC, F0bes requested changes

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +/*  PCSX2 - PS2 Emulator for PCs
We don't use spaces for indentation.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/CDVDaccess.h
> +}
Missing newline.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +//Log_SetChannel(CueParser);
Duckstation code.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +  //Log_ErrorPrintf("Cue parse error at line %u: %s", line_number, str.GetCharArray());
Duckstation code.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +  //if (error)
Duckstation code. Possibly add our own error handling?

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +    //Log_WarningPrintf("Ignoring '%*s' command", static_cast<int>(command.size()), command.data());
Duckstation code.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +  //Log_DebugPrintf("File '%s'", m_current_file->c_str());
Duckstation code.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +    //Log_WarningPrintf("Zero pregap and index 0 specified in track %u, ignoring zero pregap", m_current_track->number);
Duckstation code.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.h
> +} // namespace CueParser
Missing newline at end of file.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CMakeLists.txt
> +	CDVD/cue_parser.h
File name doesn't follow our naming scheme.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CMakeLists.txt
> +	CDVD/cue_parser.cpp
File name doesn't follow our naming scheme.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.h
> +/*  PCSX2 - PS2 Emulator for PCs
We don't use spaces as indentation.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.h
> + *  Original code from DusckStatoin by Stenznek
Typo.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.h
> +// "MSF" would be SetSector in the cdr struct
If it doesn't apply to our codebase, then remove everything about it. MSF has no meaning if it only exists on DuckStation.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +      //Log_WarningPrintf("Unknown track flag '%*s'", static_cast<int>(token.size()), token.data());
Duckstation code.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> +  //SmallString str;
If the code isn't needed, remove it.

2022-03-28 02:27 UTC, F0bes commented on pcsx2/CDVD/cue_parser.cpp
> + *  Original code from DusckStatoin by Stenznek
Typo here too.

2022-03-28 07:25 UTC, refractionpcsx2 commented on pcsx2/CDVD/CDVDaccess.h
> +}
Why is this not in the cue parser with the rest of the cue parser code since that's the only place that calls it?

2022-03-28 07:35 UTC, refractionpcsx2 commented on pcsx2/CDVD/CDVDisoReader.cpp
> +				ext = ext.parent_path() / cueFile.GetTrack(1)->filePath;
Why are you dividing as path by a path?

2022-03-30 19:26 UTC, kenshen112 commented
So, for ps1 mode. I'm assuming the track sector counts or "Modes" like MODE_SIZE_2340 for readTrack are adjusted by SetMode bit 5?

2022-04-20 03:03 UTC, kenshen112 commented
@stenzek So, I have a real quick question. I keep having an issue where the parser isn't reading all of the track files because it's hitting https://github.com/kenshen112/pcsx2/blob/c4299137efd921ab525fa781b4a6a2b24a5ca29d/pcsx2/CDVD/CueParser.cpp#L319 every time the next track has the same index 01 listing.  I'm assuming there's something about the data in DuckStation I'm not understanding? Right now it's just passing index_number as an unsigned int.

What do I not understand so far, that would cause that issue. Is that data supposed to be the entire SubChannelQ?

2022-05-14 04:24 UTC, kenshen112 commented
@stenzek If it wouldn't be too much trouble. Could I ask for a lite review on this so far? I'm trying to understand more about the math in CDVDisoReader.cpp:114 right now maxLSN seems too large. Other than that, if there's any obvious mistakes I've made so far when implementing the CueParser? I'd appreciate the feedback

2022-10-20 04:39 UTC, kenshen112 commented
Going to be splitting this into several PR's which will address several key fundamental issues with this implementation

2022-10-20 04:39 UTC, closed without merging