GameDB: Japanese entries Batch 2
PCSX2/pcsx2 pull request #5973
Opened 2022-04-26 14:39 UTC by Mrlinkwii

### Description of Changes

Adds missing serial form the GameDB 
### Rationale behind Changes

a more complete Gamedb 
### Suggested Testing Steps

make sure CI passes

2022-04-26 14:42 UTC, refractionpcsx2 commented on bin/resources/GameIndex.yaml
> +  name: "Shuffle! on the stage - DX Pack"
DX Pack should be "Deluxe Pack" and should probably be in [ ] like the Limited Edition things etc.

2022-04-26 15:06 UTC, lightningterror commented on bin/resources/GameIndex.yaml
> +  name: "oukoku no Kusabi Hiiro no Kakera 3"
Soukoku instead of oukoku, upper one too.

2022-04-26 15:31 UTC, refractionpcsx2 commented on bin/resources/GameIndex.yaml
> +  name: "Suzunone Seven Rebirth knot"
You resolved this, but you still haven't done it.

2022-04-26 23:00 UTC, RedDevilus requested changes

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Suika AS Eternal Name [First Limited Edition]"
```suggestion
  name: "Suika A.S+ Eternal Name [First Press Limited Edition]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Soukoku no Kusabi Hiiro no Kakera 3 [Limited Edition]"
```suggestion
  name: "Soukoku no Kusabi - Hiiro no Kakera 3 [Limited Edition]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Suika A.S Eternal Name[Best Edition]"
```suggestion
  name: "Suika A.S+ Eternal Name - Sweet So Sweet [Best Edition]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "SugarSpice Ano Kono Suteki na Nanimokamo"
```suggestion
  name: "Sugar+Spice! - Anoko no Suteki na Nanimokamo"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Sweet So Sweet Saishuu Shiken Kujira -Alive-"
```suggestion
  name: "Saishuu Shiken Kujira - Alive [Sweet So Sweet]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Strike Witches-Anata to Dekiru Koto [Limited Edition]"
```suggestion
  name: "Strike Witches - Anata to Dekiru Koto - A Little Peaceful Days [Limited Edition]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Strike Witches-Anata to Dekiru Koto"
```suggestion
  name: "Strike Witches - Anata to Dekiru Koto - A Little Peaceful Days"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "SweetHoneyComing [Deluxe Pack]"
```suggestion
  name: "Sweet Honey Coming [Deluxe Pack]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "SweetHoneyComing"
```suggestion
  name: "Sweet Honey Coming"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Shuumatsu Shoujo Gensou Alicematic Apocalypse[Russel Games Best]"
```suggestion
  name: "Shuumatsu Shoujo Gensou Alicematic Apocalypse [Russel Games Best]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "S.Y.K ~Shinsetsu Saiyuki [Limited Edition]"
```suggestion
  name: "S.Y.K Shinsetsu Saiyuuki [Limited Edition]"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "S.Y.K ~Shinsetsu Saiyuki"
```suggestion
  name: "S.Y.K Shinsetsu Saiyuuki"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Suzunone Seven Rebirth Knot"
```suggestion
  name: "Suzunone Seven - Rebirth Knot"
```

2022-04-26 23:00 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Shuffle! on the stage [Deluxe Pack]"
```suggestion
  name: "Shuffle! On the Stage [Deluxe Pack]"
```

2022-04-27 00:23 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "Soukoku no Kusabi Hiiro no Kakera 3"
```suggestion
  name: "Soukoku no Kusabi - Hiiro no Kakera 3"
```

2022-04-27 08:08 UTC, merged