GameDB: Add SkipDraw Range to 'Tales of the Abyss'
PCSX2/pcsx2 pull request #6269
Opened 2022-05-29 15:41 UTC by Trixarian

### Description of Changes
Adds the SkipDraw range 355, 359 that fixes the grid effect present in the Title Screen, Engave, Kaitzur Naval Port, Baticul Castle, Keterburg Port and possibly other instances within 'Tales of the Abyss'

### Rationale behind Changes
A recent commit that corrected an issue within Engave eliminated the need for the extreme SkipDraw range (100, 361) called for on the Wiki, but it also broke HPO on the Title Screen resulting in the return of the grid effect it originally corrected. 
This drove me to find a more reasonable range (355, 359) that fixes the same issues, but doesn't come with the flickering, darkening and texture stripping issues that the old range created. It also seems to correct some minor ghosting in the instances that the grid effect would be present in. It does still introduce a visual glitch into the Desert Oasis, but I feel it's an acceptable compromise for what the range corrects - at least until a future commit removes the need for SkipDraw entirely

Before:
![Title Screen 01](https://user-images.githubusercontent.com/983358/170876774-3bb2f688-05ce-48ae-af76-9917b0e4a9be.jpg)
![Baticul Castle 01](https://user-images.githubusercontent.com/983358/170877005-34c221e7-1c3b-4b4c-92aa-e8669ee794f2.jpg)
![Keterburg Bay 01](https://user-images.githubusercontent.com/983358/170877056-45e97377-5b42-4f2d-9975-6ce4acd12952.jpg)

After:
![Title Screen 02](https://user-images.githubusercontent.com/983358/170876778-536e0928-56a4-4e3e-abed-3d881cd4de8d.jpg)
![Baticul Castle 02](https://user-images.githubusercontent.com/983358/170877007-e32c9226-b4a5-4649-a36b-812764a67c54.jpg)
![Keterburg Bay 02](https://user-images.githubusercontent.com/983358/170877055-d31bdc17-78fc-4563-b3ae-7dd3c02d6163.jpg)

Visual bug introduced into Desert Oasis:
![Desert Oasis](https://user-images.githubusercontent.com/983358/170877164-a9a9f97c-6bc8-4bc5-a79e-1d538c7ce762.jpg)

### Suggested Testing Steps
Test the game to see if all possible instances of the grid effect has been corrected

2022-05-29 15:42 UTC, refractionpcsx2 commented
hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?

can you upload a GS dump showing the problem?

2022-05-29 15:44 UTC, NadoPS commented
> hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?
> 
> can you upload a GS dump showing the problem?

I think the "crystal screen" (squares) are unfixable via upscaling fixes as of now.

2022-05-29 15:46 UTC, lightningterror requested changes
Not a fan of skipdraw since it will break the effects on native resolution, maybe try using tc offsets.

2022-05-29 16:06 UTC, NadoPS commented
Here is a gs if anyone want to play around. Also the way autofixes are set up now you need to play at 6x specifically to no get ghosting.
[gs_20220529180502_Tales of the Abyss_SLUS-21386.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/8793711/gs_20220529180502_Tales.of.the.Abyss_SLUS-21386.gs.xz.zip)

2022-05-29 16:16 UTC, Trixarian commented
> hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?
> 
> can you upload a GS dump showing the problem?

I've tried all of them, including TC offsets like lightningterror suggested
Here's two gs dumps with instances of it at the title screen and keterburg bay. I can provide more if needed:
[gs_snapshots.zip](https://github.com/PCSX2/pcsx2/files/8793735/gs_snapshots.zip)

2022-05-29 16:24 UTC, Trixarian commented
> Not a fan of skipdraw since it will break the effects on native resolution, maybe try using tc offsets.

Ise tc offsets seems to have no notable effect except shifting the grid a little and causing a pixel width line at the top if values above 20 are used - similar pixel lines that appear when using HPO Normal (Vertex). Testing on Native, the only effects it seems to have is misaligning the bloom effects of the window at the title screen and the fan within the factory in Baticul

2022-05-29 16:41 UTC, seta-san commented
The grid looks a bit like the one in the Taiko drum game whose issue was closed as a won’t fix

2022-05-29 17:13 UTC, seta-san commented
> > hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?
> > can you upload a GS dump showing the problem?
> 
> I've tried all of them, including TC offsets like lightningterror suggested Here's two gs dumps with instances of it at the title screen and keterburg bay. I can provide more if needed: [gs_snapshots.zip](https://github.com/PCSX2/pcsx2/files/8793735/gs_snapshots.zip)

Does this only happen in places where the game is trying to make things look blurry/dreamy?

2022-05-29 17:25 UTC, Trixarian commented
> > > hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?
> > > can you upload a GS dump showing the problem?
> > 
> > 
> > I've tried all of them, including TC offsets like lightningterror suggested Here's two gs dumps with instances of it at the title screen and keterburg bay. I can provide more if needed: [gs_snapshots.zip](https://github.com/PCSX2/pcsx2/files/8793735/gs_snapshots.zip)
> 
> Does this only happen in places where the game is trying to make things look blurry/dreamy?

I think it's a side effect of using HPO Special (Vertex), but doesn't show up in all instances where it causes the blurry/dreamy effect. For example the blurry/dreamy effect happens in Tataroo Valley, but the grid doesn't show up at all. It seems to pop up more near areas with effects in place - like the wind effect with the trees and flags outside Baticul Castle, the moving Windmill in Engave, the waves for Kaizur Port, the snow and waves of Keterburg Bay and the panning and spinning globe effect with the Title Screen

2022-05-30 19:42 UTC, Trixarian commented
> > > hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?
> > > can you upload a GS dump showing the problem?
> > 
> > 
> > I've tried all of them, including TC offsets like lightningterror suggested Here's two gs dumps with instances of it at the title screen and keterburg bay. I can provide more if needed: [gs_snapshots.zip](https://github.com/PCSX2/pcsx2/files/8793735/gs_snapshots.zip)
> 
> Does this only happen in places where the game is trying to make things look blurry/dreamy?

Turns out I'm wrong. Whatever broke the HPO for the Title Screen also broke it for Tataroo Valley and the skyboxes for the Cutscene where Van trains Luke, and Tear attacks Van for the first time

2022-05-30 20:00 UTC, Trixarian commented
> hmm, it would be nicer to use upscaling fixes like align sprite and round sprite etc. do none of those fix it?
> 
> can you upload a GS dump showing the problem?

Grabbed more gs dumps for known instances grid effect within the game. Seems the skybox is now broken for the cutscene where Tear attacks Van after he was done introducing Combat to the player and within Tataroo Valley after being teleported there. All instances are corrected by the above SkipDraw Range, but hopefully by providing these gs dumps a better way can be found to this issue
[gs_snapshots2.zip](https://github.com/PCSX2/pcsx2/files/8800553/gs_snapshots2.zip)

2022-05-31 13:31 UTC, Trixarian commented
> This Skipdraw range break luminosity in Grand Shokmah:
> 
> ![](https://camo.githubusercontent.com/25aaa4c2d0f02f14f72586ca1aab393a24afaf1672e9cabad3cce06e59332cff/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3837383339323136343534363133343031362f3938303935383933313035343632343736382f756e6b6e6f776e2e706e67)
> 
> ![](https://camo.githubusercontent.com/b2aa9a246639ffacdccd3c46ecb2463385f730c8423cf58e1878c64252458457/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3837383339323136343534363133343031362f3938303935393033313131383134373633342f756e6b6e6f776e2e706e67)

Yeah, we noted this yesterday. It's present with the old range recommended on the Wiki too. Clearly a better way of dealing with the grid effect is sorely needed

2022-05-31 14:10 UTC, lightningterror commented
I'll close this as it isn't a good solution.

2022-05-31 14:10 UTC, closed without merging