Misc fixes
PCSX2/pcsx2 pull request #6412
Opened 2022-06-14 12:36 UTC by lightningterror

### Description of Changes

GS-d3d12: Remove scale factor clamp.
Already handled in config so it's duplicate.

GS: Make sure upscaling hacks are disabled on native res.
There was a regression that caused upscaling hacks to still be enabled on native res.

GS-wx: Disable TX x y offsets on native res:
We already gray out the option on Qt, and it should be an upscaling hack only.
### Rationale behind Changes

Regression fixes, consistency.
### Suggested Testing Steps

Make sure the options work as described.

2022-06-19 01:37 UTC, JordanTheToaster approved these changes

2022-06-19 01:47 UTC, stenzek requested changes

2022-06-19 01:47 UTC, stenzek commented on pcsx2/Pcsx2Config.cpp
> +	if (UpscaleMultiplier == 1u)
Just commenting here for completeness, this already happens in `VMManager`.

2022-06-19 01:47 UTC, stenzek commented on pcsx2/Pcsx2Config.cpp
> -	if (UpscaleMultiplier == 1 || ManualUserHacks)
We discussed this on discord, but the only issue here is the condition should be inverted (`if (UpscaleMultiplier != 1 && !ManualUserHacks)`) in `MaskUpscalingHacks()`, no need to create an additional function.

2022-06-22 10:48 UTC, stenzek approved these changes
lgtm

2022-06-22 10:58 UTC, merged