Adds the black grid fix patch for 'Tales of the Abyss' to the GameDB
PCSX2/pcsx2 pull request #6667
Opened 2022-07-18 12:44 UTC by Trixarian

Adds the patch found at https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=627849#pid627849 for Tales of the Abyss to the GameDB

### Description of Changes
This adds the patch created by sergx12 to the GameDB. It corrects the black grid effect found in the Titlescreen, Opening Cutscenes, Tataroo Valley (Night), Engeve, Kaitzur Naval Port, Baticul Castle, Grand Chokmah, Keterburg and Keterburg Bay as noted with #6497

### Rationale behind Changes
#6497 has been a long standing issue caused by the use of HPO (or any texture offset) in several areas within the game. Previously the way to correct it was by using a Skipdraw range like those found with #6269 and #6074. This had notable downsides like darkened areas, the introduction of a visual glitch to The Desert Oasis and causing a notable shift of the bloom effect on Native. This patch currently corrects the issue in all known areas without the downsides introduced by the use of Skipdraw.

### Suggested Testing Steps
Test the game to see if any visual glitches are introduced by the use of this patch

2022-07-18 12:44 UTC, Mrlinkwii commented
dose the patch effect SW mode ?

2022-07-18 12:46 UTC, Trixarian commented
> dose the patch effect SW mode ?

I don't believe so. I tested it on Native Resolution and in SW Mode to be sure that it had no negative effect on either

2022-07-18 12:50 UTC, JordanTheToaster commented
So if I understand this correctly this is an upscaling patch?

2022-07-18 12:58 UTC, lightningterror requested changes
Still this will affect sw renderer, so not a good idea.

2022-07-18 21:53 UTC, DRAGONBLE3API3C3 commented
lightningterror, does there exist a method to only have this fix apply to hardware mode?

2022-07-21 00:26 UTC, lightningterror commented
> > Still this will affect sw renderer, so not a good idea.
> 
> Is there a way to only have this fix apply to hardware mode, then? Surely we have a quarantine-esque command for game fixes, right?

With patches currently no.

2022-07-21 01:28 UTC, DRAGONBLE3API3C3 commented
> > > Still this will affect sw renderer, so not a good idea.
> > 
> > 
> > Is there a way to only have this fix apply to hardware mode, then? Surely we have a quarantine-esque command for game fixes, right?
> 
> With patches currently no.

Wouldn't that mean that there would then be potentially a large amount of game fixes that can't be automatically applied, then? Maybe I'm getting a bit ahead of myself, but I do think a simple exception system for the game fixes could be a very good thing to implement. Having your emulator be plug and play is a huge boon, in my opinion.

2022-07-23 10:00 UTC, Mrlinkwii commented
>Wouldn't that mean that there would then be potentially a large amount of game fixes that can't be automatically applied, then?

@DRAGONBLE3API3C3 
 ok , patches are for core issues  ,  not HW render issues  , patches effect both HW/SW ( even if it dosent look like it ) 

if you want to fix HW renderer issue use a GsHWFix or an upscaling fix ( read the Gameindex  documentation for options  )  if none fix the issue though luck :/

2022-07-24 15:33 UTC, closed without merging