Memory Cards: Implement conversion in Qt
PCSX2/pcsx2 pull request #6938
Opened 2022-08-28 21:40 UTC by RedPanda4552

### Description of Changes
Implements the memory card conversion option in Qt.

### Rationale behind Changes
Memory card conversion was not implemented in the initial move from wx to Qt.

### Suggested Testing Steps
Convert some memory cards, check that games still see their data on the converted cards.

2022-08-28 21:43 UTC, F0bes commented on pcsx2-qt/Settings/MemoryCardConvertDialog.h
> +};
Missing EOF newline

2022-08-29 11:01 UTC, JordanTheToaster commented
Doesn't appear to work tried to convert a 32MB card to a folder and Burnout 3 saw it as unformatted.

2022-08-29 15:54 UTC, JordanTheToaster approved these changes
All good here now LGTM.

2022-08-31 11:03 UTC, Mrlinkwii approved these changes

2022-09-01 10:32 UTC, lightningterror reviewed
Commit can be named properly with prefix.

2022-09-02 18:49 UTC, refractionpcsx2 requested changes
Gave it a quick test, and I don't think the conversion from folder to memcard is as good as it could be.

At the moment, if you have too much in your folder, it spams the console (which the user might not even have open) then it says "conversion complete!" and the user might delete the folder thinking everything is peachy, especially if they don't have the console window open.

What I would like to see:
1. When converting to memcard, check if there's enough space for the current game on the card, if not, start a new card, so like `folder_converted_1.mcd` or something.  
2. Maybe make the message to the user a bit more verbose, like "Due to the size of the folder, multiple memcards had to be created" or something.  I dunno, creative freedom :P

2022-09-11 20:35 UTC, RedPanda4552 commented
@refractionpcsx2 

- Picklist now filters options based on computed space requirements of the card
- Fixed an issue where a card containing more than 512 individual files cannot be opened (by basically changing the default number of files Windows allows a C family program to open from 512 to 1024, equal to that of Unix platforms)
- Added some notes to the UI about it stalling while processing the conversion
- Conversion menu will now refuse to open if folder memcard exceeds 64 MB of data, since no file types can hold more than that atm

2022-09-13 11:01 UTC, JordanTheToaster commented
Converted a few of my memory cards including a 32MB card and it seems to read and save fine looks good to me.

2022-09-24 12:39 UTC, Mrlinkwii commented
Converted a few of my memory cards including a 64MB memcard  , games seem happy

2022-09-24 15:16 UTC, lightningterror reviewed
Commit names should still be properly named, maybe squash some too.

2022-09-24 17:53 UTC, RedPanda4552 commented
Squashed.

2022-09-24 17:56 UTC, lightningterror reviewed
`Qt: Add dialog for memory card conversion.`

Will be better for consistency.

2022-09-24 20:06 UTC, lightningterror approved these changes

2022-10-10 20:43 UTC, kenshen112 commented
Shoved my ABSOULTE UNIT cards into the QT converter. Flipped to folder and flipped back to image with no seeming issues. Was able to browse in BIOS and see sizes and order of saves remained the same

2022-10-14 19:57 UTC, refractionpcsx2 commented
LGTM, nice work.

If you could squash things down and sort out your commit names, we can go ahead and merge :)

2022-10-14 19:57 UTC, refractionpcsx2 approved these changes

2022-10-14 20:00 UTC, RedPanda4552 commented
Squashed and rebased

2022-10-14 20:56 UTC, merged