Unified cdvd
PCSX2/pcsx2 pull request #7249
Opened 2022-10-20 04:49 UTC by kenshen112

### Description of Changes

Makes several core changes to current CDVD functionality breaking the physical disc reader cached sector buffer out to common
Adds SubchannelQ reads from physical disc functionality. Adds subQ struct to sector cache to imitate that data and subQ are separate signals and that subQ will always be filled into mechacon ram.

### Rationale behind Changes

Accuracy and better unification across CDVD reader types. Preparation for image type multitrack support CHD and CUE files
Preparation for CD-DA sound in ps1 mode as well as Dance Factory CD-DA support in image format

### Suggested Testing Steps

Test ps1, ps2 CD games. Test ps2 DVD games as soon as this is out of draft status as this will affect the iso reader and disc reader alike

2022-10-25 20:49 UTC, kenshen112 commented
If anyone has a CD reader and some physical disk PS1 or PS2 CD's this guy's read for a test.

And do note they have to have a SubchannelQ so mounted images won't be a valid test.

2022-10-31 11:13 UTC, refractionpcsx2 commented on pcsx2/CDVD/CDVDisoReader.cpp
> + *  Modified by Florin, Weirdbeardgame for PCSX2 emu
Adding a reset call and renaming a function hardly warrants adding your name to the list of people who translated libcdvd to pcsx2.

2022-10-31 11:20 UTC, refractionpcsx2 commented on pcsx2/CDVD/CDVDcommon.cpp
> +* should be common across all reader types - weirdbeard
No need to sign this off, either. I'm not sure this comment was needed, at all.

2022-10-31 19:50 UTC, kenshen112 commented
Is there anything else that needs to be addressed?

2022-10-31 20:01 UTC, F0bes requested changes

2022-10-31 20:01 UTC, F0bes commented on pcsx2/Darwin/DarwinFlatFileReader.cpp
> +
Empty line.

2022-10-31 20:01 UTC, F0bes commented on pcsx2/Darwin/DarwinFlatFileReader.cpp
> +	cdvdCacheReset();
Indentation is off for this line and the `return`.

2022-11-20 05:06 UTC, kenshen112 commented
Good to see :thumbsup:

2022-11-26 05:47 UTC, kenshen112 commented
If anyone's available. This is ready for a full review

2022-12-17 18:16 UTC, lightningterror commented
It was discussed that this doesn't really improve anything so it won't be merged, also there are alternative plans for cdvd.

2022-12-17 18:16 UTC, closed without merging