UI: Fix build with achievements disabled
PCSX2/pcsx2 pull request #8458
Opened 2023-03-21 03:52 UTC by TellowKrinkle

### Description of Changes
Makes the no achievements config build again
Fixes #8457

### Rationale behind Changes
Successfully building is good

### Suggested Testing Steps
@DNDEBUG @LeCharlatan please test

2023-03-21 10:10 UTC, DNDEBUG commented
it works

2023-03-21 10:49 UTC, stenzek requested changes

2023-03-21 10:49 UTC, stenzek commented on pcsx2/Frontend/CommonHotkeys.cpp
> +#ifdef ENABLE_ACHIEVEMENTS
This bit shouldn't be needed - `ChallengeModeActive()` returns false when it's not compiled in: https://github.com/PCSX2/pcsx2/blob/280a41806f8a212597deac50a466fb052729c19e/pcsx2/Achievements.h#L60-L63

2023-03-23 13:53 UTC, stenzek approved these changes

2023-03-24 04:48 UTC, merged