OSD: Input recording overlap fixed
PCSX2/pcsx2 pull request #9211
Opened 2023-07-09 16:54 UTC by sestain

### Description of Changes
Draws the input recording overlay first and then the performance overlays.

### Rationale behind Changes
Closes #8330.

### Suggested Testing Steps
Check by playing an input recording while all OSD settings are on.

2023-07-09 18:42 UTC, Mrlinkwii approved these changes
![image](https://github.com/PCSX2/pcsx2/assets/17685135/fda6010c-61bb-4bca-851e-26c9cd2616d8)
 looks good

2023-07-10 03:02 UTC, stenzek requested changes

2023-07-10 03:02 UTC, stenzek commented on pcsx2/ImGui/ImGuiOverlays.cpp
> +float position_y = 0;
Please don't add additional global variables, polluting the global namespace.

This is also going to break if you turn recording off. Have a local in the parent function, and pass it in by reference.

2023-07-10 10:56 UTC, stenzek commented on pcsx2/ImGui/ImGuiOverlays.cpp
> +	float position_y;
Initialize this with zero, then in `DrawInputRecordingOverlay()`, add `margin` to it. That way if something gets added in the middle later, it won't break.

2023-07-10 13:09 UTC, kamfretoz commented
This is just my two cents... Instead of cramming the input recording overlay on the top right along with performance stats, why not just put it on the bottom left just above the controllers input indicator? it fits more there imo.

2023-07-10 13:23 UTC, refractionpcsx2 commented
I don't think adding to the y position is really the solution, what if you stop input recording? it's going to stay offset.

I suggest you do what Stenzek originally suggested and move the assignment off in to a separate function you can call from two places. Also the add of the initial margin probably should be in RenderOverlays(), otherwise if you're not recording, there won't be a margin.

2023-07-10 14:32 UTC, sestain commented
> I don't think adding to the y position is really the solution, what if you stop input recording? it's going to stay offset.

What do you mean exactly by "what if you stop input recording? it's going to stay offset."?

2023-07-10 14:45 UTC, refractionpcsx2 commented
I mean you're offsetting the OSD to make room for the input recording information, then stop the input recording, the OSD is going to still be offset, no?

2023-07-10 14:49 UTC, sestain commented
Start of emulation
![image](https://github.com/PCSX2/pcsx2/assets/35299377/ac9cb519-9a82-4482-b1c0-e49ad68f96f6)
Start of input recording
![image](https://github.com/PCSX2/pcsx2/assets/35299377/9a5e7061-28e2-4aa4-8d60-c1332ed0a5d1)
End of input recording by stopping it
![image](https://github.com/PCSX2/pcsx2/assets/35299377/f378dc71-e163-4f0a-b721-d6fa4ec0a4f0)

2023-07-10 16:38 UTC, refractionpcsx2 commented
Huh, alright then.

2023-07-11 01:01 UTC, merged