GameDB: Sort and append missing entried from Redump
PCSX2/pcsx2 pull request #9671
Opened 2023-07-30 01:05 UTC by refractionpcsx2

### Description of Changes
Add missing entries and reorder some out of order entries.  List was provided by the Redump team (thank you guys for your hard work putting the list together).

python scripts to append these was done with the help of ChatGPT, some of the region/languages may be incorrect, but they can be amended if need be.

### Rationale behind Changes
Missing stuff is bad.

### Suggested Testing Steps
Watch the CI

2023-07-30 01:10 UTC, RedDevilus commented
![image](https://github.com/PCSX2/pcsx2/assets/24227051/0f3617ab-c56c-4dd3-a546-93932411a536)

2023-07-30 01:18 UTC, RedDevilus requested changes

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  name: "XI [sÃ¡i] - XI-Go"
![image](https://github.com/PCSX2/pcsx2/assets/24227051/d280e6fe-64f7-485e-a0c4-2d50a4f0c4c3)

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  region: "PAL-Unk"
PAL-E just like others, it probably set of Gamedb lint validator issue

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  region: "PAL-Unk"
Actually just replace Pal-Unk with E or something (if its PAL-A, issue for later)

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> -SCED-52260:
Undo delete

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> -SCED-52261:
Undo delete

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> -SLPM-66707:
Undo delete

2023-07-30 01:18 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> -SLPS-25922:
Undo delete

2023-07-30 01:27 UTC, RedDevilus commented
Fixes https://github.com/PCSX2/pcsx2/issues/4434

2023-07-30 01:33 UTC, RedDevilus commented on bin/resources/GameIndex.yaml
> +  region: "PAL-Unk"
Or just make sure the Europe flag is applied for the Pal-unk, otherwise it's a question mark. Oh well easier to fix new entries

2023-07-30 01:37 UTC, merged

2023-07-30 14:13 UTC, mariomadproductions commented
@refractionpcsx2 Please could you post the python script used, and the list from redump?

2023-07-30 14:38 UTC, refractionpcsx2 commented
There was a couple :P but sure

[source_list.csv](https://github.com/PCSX2/pcsx2/files/12209441/source_list.csv)
[pyscripts.zip](https://github.com/PCSX2/pcsx2/files/12209443/pyscripts.zip)

2023-07-30 14:56 UTC, mariomadproductions commented
> There was a couple :P but sure
> 
> [source_list.csv](https://github.com/PCSX2/pcsx2/files/12209441/source_list.csv) [pyscripts.zip](https://github.com/PCSX2/pcsx2/files/12209443/pyscripts.zip)

Thanks

2023-07-30 19:12 UTC, RedDevilus commented
12621 games on record hmm, might still be missing entries on redump from specific areas like Turkey, Russia or more. Still nice to see it up. with about 57K lines for GameDB.

2023-07-30 21:58 UTC, RedDevilus commented
> > 12621 games on record hmm, might still be missing entries on redump from specific areas like Turkey, Russia or more. Still nice to see it up. with about 57K lines for GameDB.
> 
> I made the redump serial list that refraction used, it's definitely not missing any retail games in redump such as those from Turkey/Russia. Redump's disc count is larger due to Preprod/Demo/Other PS2 discs that do not have serials.

Well was just thinking about games not being uploaded to github yet, not saying that it's not the complete redump csv. As some sites have information about discs that redump doesn't have.

Maybe we could do compare check PCSX2 GameDB yaml against redump itself. I meant no offense perhaps just wrong idea about it.

2023-07-30 22:21 UTC, RedDevilus commented
> > As some sites have information about discs that redump doesn't have.
> 
> There are definitely many serials that are not yet in redump: only a handful from USA/PAL but quite a few from Asia/Korea. The redump wiki tracks missing games, that can be used for updating the PCSX2 yaml to be more complete. I can make another list from the redump wiki, if desired.

Perhaps for future goal, improving both sides would be nice but not sure how much this help the average user, maybe i'm just a bit too passionate for it :P

2023-07-30 22:47 UTC, refractionpcsx2 commented
We usually put PAL-Unk if you don't know what languages they are, or if you know how many languages they have, you can use the "Multi" extension, so like PAL-M5 for a game with 5 languages

2023-07-30 22:48 UTC, RedDevilus commented
> Improving the GameDB is also something I want, here's a short list of the missing USA/PAL serials to add to the GameDB if you want to do it. The Asia/Korea list is much longer, will require automation again.
> 
> Note: I have only used "PAL" for the PS2 demos, though some may be region-specific.
> 
> ```
> SCUS-97118, NTSC-U, NFL GameDay 2001 [Demo]
> SCUS-97237, NTSC-U, NCAA Final Four 2003 [Demo]
> SCUS-97603, NTSC-U, Buzz (single disc) [Demo]
> SCUS-97628, NTSC-U, Buzz (multi disc) [Demo]
> SCUS-97860, NTSC-U, Twisted Metal - Black Online [Public Beta]
> SCUS-97862, NTSC-U, Network Adapter Start-Up Disc Network [Beta v.2.0]
> SLUS-21257, NTSC-U, Need for Speed: Most Wanted
> SLUS-29051, NTSC-U, Freaky Flyers [Rating Pending version]
> 
> SCES-55484, PAL-IN, World Quiz 2009
> 
> SCED-51097, PAL, Gran Turismo: Nissan 350Z Edition [Demo]
> SCED-51878, PAL, Ratchet & Clank 2 [Demo]
> SCED-53678, PAL, Fire It Up Kids [Demo]
> SCED-54190, PAL, Forbidden Siren 2 [Demo]
> SLED-50473, PAL, Time Crisis II [Demo]
> SLED-50626, PAL, Shaun Palmer's Pro Snowboarder [Demo]
> SLED-50782, PAL, Metal Gear Solid 2: Sons of Liberty [Demo]
> SLED-53085, PAL, UEFA Champions League 2004-2005 [Demo]
> SLED-53105, PAL, Metal Gear Solid 3: Snake Eater [Demo]
> SLED-53126, PAL, Fight Night Round 2 [Demo]
> SLED-53586, PAL, NHL 06 [Demo]
> SLES-53392, PAL, Spartan: Total Warrior [Demo]
> ```

The other thing that we need to fix is the Pal-unk to show what languages they have and more than 3 turned into M4 for 4 languages or ex. M7 for 7. Still PCSX2 kinda combines region with supported languages but labels it as region which is a disparity compared to redump, it's kinda the style that the sony via wayback has.

2023-07-30 23:00 UTC, RedDevilus commented
> Redump has decent but not complete coverage for languages, so this could also be automated to improve the GameDB. I'm mostly interested in getting the many missing Asia/Korea serials into GameDB first though, WIP.
> 
> If the region code also carries language info, how should I deal with an Asian/Korean serial where the game has not been localised? (i.e. the game is in English only) - e.g. SCKA-XXXXX where the game is in English only. Or is language only included in the PAL region codes?

I think only PAL has a lot of treatment in terms of languages because the asian entries have less checkers, so mostly just say NTSC-J, so more-so the actual region than the available languages. I think in the future the idea is to split up actual game region and another variable for available languages.

2023-07-30 23:08 UTC, RedDevilus commented
That disparity might've been me trying to fix it up for the Asian entries and fucking a NTSC-E by accident because -E is Europe. It's kinda confusing still as -E can be interpreted as English for sure.

2023-07-30 23:13 UTC, RedDevilus commented
I guess that is fair, GameDB is and always has been a tinkerfest, but if it can get closer to be a good list for serials, the better. And someone who feels like fixing Unk later, can always do it. Also need to check missing automatic fixes for the new serials so that's also a time-consuming task ignoring the region stuff.

2023-08-02 15:45 UTC, RedDevilus commented
11523 -> 12621 games on record (+1098)